#!/usr/bin/env python
import sys

from flake8.main import git

if __name__ == '__main__':
    sys.exit(
        git.hook(
            strict=True,  # Return total number of error/violation
            lazy=False  # Only parse staged files
        )
    )
